/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package aeroporto;

import java.util.*;

// ----------- << imports@AAAAAAF+T15Y5g0mgEc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+T15Y5g0mgEc= >>
// ----------- >>
public class Gate {
	//-----------------------------------INIZIALIZZAZIONE VARIABILI-------------------------------------------------------------
    
	// ----------- << attribute.annotations@AAAAAAF+T15Y5g0qNLs= >>
    // ----------- >>
    private String ID;
    
    private static Integer numero=0;

    // ----------- << attribute.annotations@AAAAAAF+T15Y5g0r+Nk= >>
    // ----------- >>
    private boolean isOccupied;

    // ----------- << attribute.annotations@AAAAAAF+V/1fL3S22Qw= >>
    // ----------- >>
    private static Set<Gate> listaGate = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF+T15Y5g0pZUE= >>
    // ----------- >>
    //-----------------------------------COSTRUTTORE------------------------------------------------------------------
    public Gate() {
    	this.setID("G-" + numero.toString());
    	numero++;
    	this.isOccupied=false;
    	listaGate.add(this);
    }
    
    //-----------------------------------METODI SET/GET------------------------------------------------------------------
    String getID() {
        return ID;
    }

    boolean isIsOccupied() {
        return isOccupied;
    }

    void setID(String ID) {
        this.ID = ID;
    }

    void setIsOccupied(boolean isOccupied) {
        this.isOccupied = isOccupied;
    }

    // ----------- << method.annotations@AAAAAAF+V/4683gKY2Y= >>
    // ----------- >>
    public static Set<Gate> getListaGate() {
    // ----------- << method.body@AAAAAAF+V/4683gKY2Y= >>
    	return listaGate;
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+T15Y5g0mgEc= >>
// ----------- >>
}