/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package aeroporto;

import java.util.Date;



// ----------- << imports@AAAAAAF+T15Y5AzuAdg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+T15Y5AzuAdg= >>
// ----------- >>
public class Prenotazione {
	//----------------------------------------------------------------------------------------INIZIALIZZAZIONE VARIABILI--------
	
    // ----------- << attribute.annotations@AAAAAAF+T15Y5QzytDE= >>
    // ----------- >>
    private String nome;

    // ----------- << attribute.annotations@AAAAAAF+T15Y5Qzzo9o= >>
    // ----------- >>
    private String cognome;

    // ----------- << attribute.annotations@AAAAAAF+T15Y5Qz0VME= >>
    // ----------- >>
    private Date dataNascita;

    // ----------- << attribute.annotations@AAAAAAF+T15Y5Qz1Njk= >>
    // ----------- >>
    private String nCartaIdentita;

    // ----------- << attribute.annotations@AAAAAAF+T15Y5Qz31FM= >>
    // ----------- >>
    private String IDBiglietto;

    // ----------- << attribute.annotations@AAAAAAF+T15Y5Qz4YtI= >>
    // ----------- >>
    private boolean certificazioneCov19;

    // ----------- << attribute.annotations@AAAAAAF+T15Y5Qz5Jwk= >>
    // ----------- >>
    private boolean priorita;

    // ----------- << attribute.annotations@AAAAAAF+T15Y5Qz6XQw= >>
    // ----------- >>
    private int nBagagli;

    // ----------- << attribute.annotations@AAAAAAF+T15Y5Azx+R8= >>
    // ----------- >>
    private Volo Volo;
    
    private static Integer numero=0;
    
    //------------------------------------------------------------------------------------METODI SET/GET------------------------
    public String getNome() {
        return nome;
    }

    public String getCognome() {
        return cognome;
    }

    public Date getDataNascita() {
        return dataNascita;
    }

    public String getNCartaIdentita() {
        return nCartaIdentita;
    }

    public String getIDBiglietto() {
        return IDBiglietto;
    }

    public boolean isCertificazioneCov19() {
        return certificazioneCov19;
    }

    public boolean isPriorita() {
        return priorita;
    }

    public int getNBagagli() {
        return nBagagli;
    }

    public Volo getVolo() {
        return Volo;
    }

    void setNome(String nome) {
        this.nome = nome;
    }

    void setCognome(String cognome) {
        this.cognome = cognome;
    }

    void setDataNascita(Date dataNascita) {
        this.dataNascita = dataNascita;
    }

    void setNCartaIdentita(String nCartaIdentita) {
        this.nCartaIdentita = nCartaIdentita;
    }


    void setIDBiglietto(String IDBiglietto) {
        this.IDBiglietto = IDBiglietto;
    }

    void setCertificazioneCov19(boolean certificazioneCov19) {
        this.certificazioneCov19 = certificazioneCov19;
    }

    void setPriorita(boolean priorita) {
        this.priorita = priorita;
    }

    void setNBagagli(int nBagagli) {
        this.nBagagli = nBagagli;
    }

    void setVolo(Volo Volo) {
        this.Volo = Volo;
    }

    //-------------------------------------------------------------------------------------COSTRUTTORE--------------------------
    // ----------- << method.annotations@AAAAAAF+T15Y5Qz7mRw= >>
    // ----------- >>
	public Prenotazione(String idVolo, String nome, String cognome, String nCartaId, int nBagagli, boolean priorita, Date nascita) {
    // ----------- << method.body@AAAAAAF+T15Y5Qz7mRw= >>
		setIDBiglietto("P-"+numero.toString());
    	numero++;
    	setCertificazioneCov19(false);
    	setNome(nome);
    	setCognome(cognome);
    	setNCartaIdentita(nCartaId);
    	setNBagagli(nBagagli);
    	setPriorita(priorita);
    	setDataNascita(nascita);
    // ----------- >>
    }
    //--------------------------------------------------------------------------------METODO INSERISCI CERTIFICAZIONE----------
    // ----------- << method.annotations@AAAAAAF+T15Y5Qz8zFc= >>
    // ----------- >>
    public void inserisciCertificazione() {
    // ----------- << method.body@AAAAAAF+T15Y5Qz8zFc= >>
    	this.setCertificazioneCov19(true);
    	System.out.println("con questa modifica dichiari di essere in possesso di green pass");
    // ----------- >>
    }
    
// ----------- << class.extras@AAAAAAF+T15Y5AzuAdg= >>
// ----------- >>
}