/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package aeroporto;

// ----------- << imports@AAAAAAF+T15Y5g0uTec= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+T15Y5g0uTec= >>
// ----------- >>
public enum TipoVolo {
    DIRETTO,
    SCALO;

// ----------- << enum.extras@AAAAAAF+T15Y5g0uTec= >>
// ----------- >>
}